//--------------------------------------------
// TestHelper
//
// This header is basically an include all type helper for Test*.cpp files
// therefore greatly reducing duplication
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wall"
#pragma GCC diagnostic ignored "-Wpedantic"
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#include <gmock/gmock.h>
#pragma GCC diagnostic pop

#include <iostream>
#include <istream>
#include <sstream>
#include <memory>
// AutoGenerated
#include "../Src/ArgsForEchoJoiner.h"
#include "../Src/BashStaticCodeGetter.h"
#include "../Src/CommaSpaceArgsForEchoJoiner.h"
#include "../Src/DoubleQuoteStringTokenGenerator.h"
#include "../Src/ErrorCollector.h"
#include "../Src/ErrorCollectorImpl.h"
#include "../Src/IndentGenerator.h"
#include "../Src/IndentGeneratorImpl.h"
#include "../Src/KeywordGetter.h"
#include "../Src/KeywordGetterImpl.h"
#include "../Src/LineReader.h"
#include "../Src/Preprocessor.h"
#include "../Src/Printer.h"
#include "../Src/ReadingPreprocessor.h"
#include "../Src/StaticCodeGetter.h"
#include "../Src/StdErrErrorPrinter.h"
#include "../Src/StdInLineReader.h"
#include "../Src/StreamLineReader.h"
#include "../Src/StringTokenGenerator.h"
// End AutoGenerated
//--------------------------------------------
