#include "cppstaticcodegetter.h"

CppStaticCodeGetter::CppStaticCodeGetter() {}

std::string CppStaticCodeGetter::GetBeforePreHeader()
{
    return std::string("/**************************************************\n"
                       " *                                                *\n"
                       " * Generated By GenGen : Code Generator Generator *\n"
                       " *                              -Bhathiya Perera  *\n"
                       " *                                                *\n"
                       " *************************************************/\n");
}
std::string CppStaticCodeGetter::GetAfterPreHeader()
{
    return std::string("#include <iostream>\n");
}
std::string CppStaticCodeGetter::GetAfterHeader()
{
    return std::string("int main(int argc, char** argv){\n");
}
std::string CppStaticCodeGetter::GetBeforeFooter()
{
    return std::string("    return 0;\n}\n");
}
std::string CppStaticCodeGetter::GetAfterFooter()
{
    return std::string();
}
std::string CppStaticCodeGetter::GetAfterPostFooter()
{
    return std::string("//-------------------------------------------------\n");
}
unsigned int CppStaticCodeGetter::GetStartingIndent()
{
    return 1;
}
